[env]
TERM = "xterm-256color"

[window]
decorations = "None"
startup_mode = "Maximized"
decorations_theme_variant = "Dark"

[font]
# normal.family = "JetBrainsMono Nerd Font"
normal = { family = "JetBrainsMono Nerd Font Mono", style = "Medium" }

size = 10

[colors]
# Цвета при выборе папки при автодополнении
normal.green = "#5a5a5a" #Цвет фона
normal.blue = "#c5c585" #Цвет букв
