wallpaper {
  monitor = DP-1
  path = /home/roman/wallpapers/fog_tree_art_125815_1920x1080.jpg
}

wallpaper {
  monitor = HDMI-A-1
  path = /home/roman/wallpapers/fog_tree_art_125815_1920x1080.jpg
}
splash = false
