#! /bin/sh

# Переключение языка на оба шифта
setxkbmap -layout 'us,ru' -option 'grp:shifts_toggle,compose:menu'

pgrep -x sxhkd >/dev/null || sxhkd &
alacritty &
firefox &
polybar &
flameshot &
korganizer &
qbittorrent &
thunderbird &
picom &
/opt/nekoray/nekoray -tray -appdata &
"$HOME"/Telegram/Telegram &
"$HOME"/.config/polybar/launch.sh &
"$HOME"/.config/polybar/pulse-control &

bspc monitor DP-0 -d VI VII VIII IX X
bspc monitor HDMI-0 -d I II III IV V

# Рамки и отступы
bspc config border_width 3
bspc config window_gap 6

# Цвет рамки в разных состояниях:
bspc config normal_border_color "#000000"
bspc config active_border_color "#E0FFFF"
bspc config focused_border_color "#FFB52A"
# bspc config active_border_color "#D384AA"
# bspc config focused_border_color "#344756"

# Цвет пространства при выборе положения нового окна
bspc config presel_feedback_color "#595B82"

# Коэффициент разделения. Сколько процентов останется от родительского окна при открытии нового.
bspc config split_ratio 0.52

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Firefox desktop=II
bspc rule -a TelegramDesktop desktop='^6' focus=on
bspc rule -a thunderbird desktop='^6'
bspc rule -a korganizer desktop='^2'
bspc rule -a alacritty desktop='^7'

# Фокус окна при наведении курсора
bspc config focus_follows_pointer true
bspc config pointer_modifier super
