#! /bin/sh

pgrep -x sxhkd >/dev/null || sxhkd &
polybar &
flameshot &
"$HOME"/Telegram/Telegram &

bspc monitor DP-0 -d VI VII VIII IX X
bspc monitor HDMI-0 -d I II III IV V

# Рамки и отступы
bspc config border_width 1
bspc config window_gap 12

# Цвет рамки в разных состояниях:
bspc config normal_border_color "#0A1F32"
bspc config active_border_color "#2D384A"
bspc config focused_border_color "#344756"

# Цвет пространства при выборе положения нового окна
bspc config presel_feedback_color "#595B82"

# Коэффициент разделения. Сколько процентов останется от родительского окна при открытии нового.
bspc config split_ratio 0.52

bspc config borderless_monocle true
bspc config gapless_monocle true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Фокус окна при наведении курсора
bspc config focus_follows_pointer true
bspc config pointer_modifier super
