#! /bin/sh

echo "$PATH" >"$HOME"/path.log

pgrep -x sxhkd >/dev/null || sxhkd &
polybar &
picom &
rofi &
firefox &
flameshot &
korganizer &
thunderbird &
nitrogen --restore &
/opt/nekoray/nekoray -tray -appdata &
/opt/urserver/urserver-start --no-manager --no-notify &
"$HOME"/Telegram/Telegram &
"$HOME"/.config/polybar/launch.sh &
"$HOME"/.config/polybar/pulse-control &
qbittorrent &

# Переключение языка на оба шифта
setxkbmap -layout 'us,ru' -option 'grp:shifts_toggle,compose:menu' >~/xkb.log

# Настройка мониторов
# xrandr -q | grep connected
bspc monitor DP-0 -d VI VII VIII IX X
bspc monitor HDMI-0 -d I II III IV V

# Рамки и отступы
bspc config border_width 2
bspc config window_gap 6

# Цвет рамки в разных состояниях:
bspc config normal_border_color "#1d2021"
bspc config active_border_color "#ebdbb2"
bspc config focused_border_color "#d79921"

# Цвет пространства при выборе положения нового окна
bspc config presel_feedback_color "#595B82"

# Коэффициент разделения. Сколько процентов останется от родительского окна при открытии нового.
bspc config split_ratio 0.52

bspc config borderless_monocle true
bspc config gapless_monocle true

# Взаимодействие с окнами мышью
bspc config focus_follows_pointer true
bspc config pointer_modifier super

# xprop | grep WM_CLASS
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a firefox_firefox desktop='^2' focus=off
# bspc rule -a Navigator desktop='^2'
bspc rule -a TelegramDesktop desktop='^6'
bspc rule -a thunderbird desktop='^6'
bspc rule -a korganizer desktop='^1'
bspc rule -a qBittorrent desktop='^5' follow=off
bspc rule -a 'Docker Desktop' desktop='^8'
bspc rule -a Google-chrome desktop='^3'
